name: Commpile package for arch

description: 'Fromm this action you can commpile Packages for arch linux'

on:
  workflow_dispatch:
    inputs:
      repo:
          description: 'package Repo link'
          required: false
      token:
          description: 'github token to push the package'
          required: false
      email:
          description: 'email for git config'
          required: false
      username:
          description: 'username for git config'
          required: false 
      output:
          description: 'output repo Name Not Url where the package should get uploaded'
          required: false   


env:
  TZ: Asia/Kolkata
  REPO: ${{ github.event.inputs.repo }}
  GITHUB_TOKEN: ${{ github.event.inputs.token }}
  EMAIL: ${{ github.event.inputs.email }}
  USERNAME: ${{ github.event.inputs.username }}
  OUTPUT: ${{ github.event.inputs.output }}


jobs:
  run-archlinux:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull Arch Linux Docker image
      run: docker pull archlinux:latest

    - name: Run commands in Arch Linux container
      run: |
        docker run --rm archlinux:latest bash -c "
          echo 'Running commands in Arch Linux container';
          pacman -Syu --noconfirm;
          # Add your commands here
          pacman -S base-devel --noconfirm
        "