name: Build and Upload Arch Package

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository URL'
        required: true
      token:
        description: 'GitHub Token'
        required: true
        secret: true
      email:
        description: 'User Email'
        required: true
      username:
        description: 'Username'
        required: true

env:
  TZ: Asia/Kolkata

jobs:
  build-arch-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull Arch Linux Docker image
      run: docker pull archlinux:latest

    - name: Build Arch Linux package
      run: |
        docker run --rm \
          -e EMAIL='${{ github.event.inputs.email }}' \
          -e USERNAME='${{ github.event.inputs.username }}' \
          -v $(pwd):/workspace -w /workspace archlinux:latest bash -c "
            echo 'Building Arch Linux package';
            pacman -Syu --noconfirm;
            pacman -S base-devel git --noconfirm;
            git config --global user.email '${{ github.event.inputs.email }}';
            git config --global user.name '${{ github.event.inputs.username }}';
            git clone '${{ github.event.inputs.repo }}' source;
            cd source;
            makepkg --noconfirm;
            cp -r *.tar.zst /workspace;
          "

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: '*.pkg.tar.zst'
