name: Commpile package for arch

on:
  workflow_dispatch:
    inputs:
      repo:
          description: 'package Repo link'
          required: true
      token:
          description: 'github token to push the package'
          required: true
      email:
          description: 'email for git config'
          required: true
      username:
          description: 'username for git config'
          required: true 
      output:
          description: 'output repo Name Not Url where the package should get uploaded'
          required: true   


env:
  TZ: Asia/Kolkata
  REPO: ${{ github.event.inputs.repo }}
  GITHUB_TOKEN: ${{ github.event.inputs.token }}
  EMAIL: ${{ github.event.inputs.email }}
  USERNAME: ${{ github.event.inputs.username }}
  OUTPUT: ${{ github.event.inputs.output }}

jobs:
  build:
    runs-on: ubuntu-22.04
    
    steps:
    steps:
      - name: Initializing environment
        run: |
          sudo apt upgrade -y
          sudo apt install -y bc bison build-essential ccache curl flex glibc-source g++-multilib gcc-multilib binutils-aarch64-linux-gnu git gnupg gperf imagemagick lib32ncurses5-dev lib32readline-dev lib32z1-dev liblz4-tool libncurses5 libncurses5-dev libsdl1.2-dev libssl-dev libwxgtk3.0-gtk3-dev libxml2 libxml2-utils lzop pngcrush rsync schedtool squashfs-tools xsltproc zip zlib1g-dev python2 tmate ssh neofetch
          neofetch
        
    - name: Install Docker
      run: curl -L https://github.com/alex5402/Arch-Linux-Package-builder/raw/master/install-docker.sh | sh
      
    - name: Setup And Compile Package
      run: curl -L https://github.com/alex5402/Arch-Linux-Package-builder/raw/master/install-arch.sh $OUTPUT $USERNAME $EMAIL $GITHUB_TOKEN $OUTPUT | sh
