name: Build and Upload Arch Package

on:
  workflow_dispatch:
    inputs:
      repo:
        description: 'Repository URL'
        required: true

env:
  TZ: Asia/Kolkata

jobs:
  build-arch-package:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v2

    - name: Pull Arch Linux Docker image
      run: docker pull archlinux:latest

    - name: Build Arch Linux package
      run: |
         run: |
         docker run --rm \
          -v $(pwd):/workspace -w /workspace archlinux:latest bash -c "
            echo 'Building Arch Linux package';
            pacman -Syu --noconfirm;
            pacman -S base-devel git sudo --noconfirm;

            # Create a non-root user
            sudo useradd -m builder;

            # Switch to the non-root user
            sudo -u builder bash -c '
              git clone \"${{ github.event.inputs.repo }}\" source;
              cd source;
              makepkg -si --noconfirm;
              cp *.pkg.tar.zst /workspace/;
            '
          "

    - name: Upload artifact
      uses: actions/upload-artifact@v4
      with:
        name: build-output
        path: '*.tar.zst'
